// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"github.com/mzkki/ottodot-trial/internal/delivery/http/admin"
	"github.com/mzkki/ottodot-trial/internal/delivery/http/booking"
	"github.com/mzkki/ottodot-trial/internal/delivery/http/page"
	"github.com/spf13/viper"
	"go.uber.org/zap"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeHandlers(db *gorm.DB, config *viper.Viper) (*Handlers, error) {
	parentRepository := ProvideParentRepo(db)
	studentRepository := ProvideStudentRepo(db)
	trialClassRepository := ProvideTrialClassRepo(db)
	bookingRepository := ProvideBookingRepo(db)
	paymentAttemptRepository := ProvidePaymentAttemptRepo(db)
	paymentGateway := ProvidePaymentGateway()
	gormTransactionManager := ProvideTxManager(db)
	bookingUseCase := ProvideBookingUseCase(parentRepository, studentRepository, trialClassRepository, bookingRepository, paymentAttemptRepository, paymentGateway, gormTransactionManager)
	logger, err := ProvideLogger(config)
	if err != nil {
		return nil, err
	}
	pageHandler := ProvidePageHandler(bookingUseCase, logger)
	bookingHandler := ProvideBookingHandler(bookingUseCase, logger)
	adminHandler := ProvideAdminHandler(bookingUseCase, logger)
	handlers := &Handlers{
		Page:    pageHandler,
		Booking: bookingHandler,
		Admin:   adminHandler,
		Logger:  logger,
		Config:  config,
	}
	return handlers, nil
}

// wire.go:

type Handlers struct {
	Page    *page.PageHandler
	Booking *booking.BookingHandler
	Admin   *admin.AdminHandler
	Logger  *zap.Logger
	Config  *viper.Viper
}
